name: Compilar APK de Comunity TV

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Especificamos Gradle 8.7 (la versión que necesita el plugin de Android)
      - name: Configurar Gradle 8.7
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      # Ahora compilamos
      - name: Compilar APK Debug
        run: gradle assembleDebug

      - name: Subir APK a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Comunity-TV-Debug
          path: app/build/outputs/apk/debug/app-debug.apk
